language: node_js
node_js:
  - 'node'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always

stages:
  - test
  - name: update-algolia
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    - stage: test
      script:
        - yarn test-ci

    - stage: update-algolia
      script: yarn update-speakers
